import type { ApplicantWorkflowPageConfig, ApplicantWorkflowPageId } from '@/lib/types';

export const APPLICANT_WORKFLOW_CONFIG: Record<ApplicantWorkflowPageId, ApplicantWorkflowPageConfig> = {
  'applicant-interview-review': {
    id: 'applicant-interview-review', eyebrow: 'Interview · Select availability',
    title: 'Choose an interview timeslot',
    description: 'Select an available time, or request another time if none of the suggested slots work for you.',
    status: 'Action required', statusTone: 'warning', activeRoute: '/apply/interviews',
    backLabel: 'My Interviews', backRoute: '/apply/interviews',
    primaryLabel: 'Submit Timeslot', primaryRoute: '/apply/applicant-interview-confirmation?applicationId=app-poly-2027',
    notice: 'Submitting availability does not confirm the interview. We will notify you when a final time is scheduled.',
    details: [
      { label: 'First preference', value: '27 Aug 2026 · 2:30 PM SGT' },
      { label: 'Second preference', value: '28 Aug 2026 · 10:00 AM SGT' },
      { label: 'Interview format', value: 'Microsoft Teams · 45 minutes' },
      { label: 'Mentor', value: 'Aisha Rahman · Digital Hub' },
    ],
  },
  'applicant-interview-confirmation': {
    id: 'applicant-interview-confirmation', eyebrow: 'Interview · Availability submitted',
    title: 'Your availability has been submitted',
    description: 'The interview team will review your selected time and confirm the final interview slot.',
    status: 'Awaiting confirmation', statusTone: 'info', activeRoute: '/apply/interviews',
    backLabel: 'My Interviews', backRoute: '/apply/interviews',
    primaryLabel: 'View Application', primaryRoute: '/apply/applications/app-poly-2027',
    secondaryLabel: 'Back to My Interviews', secondaryRoute: '/apply/interviews',
    notice: 'No action is needed while the interview team confirms a time.',
    details: [
      { label: 'Submitted', value: '21 Aug 2026 · 10:42 AM SGT' },
      { label: 'Preferred times', value: '27 Aug 2:30 PM; 28 Aug 10:00 AM' },
      { label: 'Expected update', value: 'Within 2 working days' },
    ],
  },
  'applicant-interview-reschedule-review': {
    id: 'applicant-interview-reschedule-review', eyebrow: 'Interview · Time change request',
    title: 'Review your suggested interview time',
    description: 'Compare the confirmed slot with your proposed alternative before sending the request to your mentor.',
    status: 'Review required', statusTone: 'warning', activeRoute: '/apply/interviews',
    backLabel: 'Suggest another time', backRoute: '/apply/interview-proposed',
    primaryLabel: 'Submit Request', primaryRoute: '/apply/applications/app-ai-2027',
    secondaryLabel: 'Edit Request', secondaryRoute: '/apply/interview-proposed',
    notice: 'Your original interview remains scheduled until the alternative time is confirmed.',
    details: [
      { label: 'Original slot', value: '28 Aug 2026 · 3:00 PM SGT' },
      { label: 'Suggested time', value: '31 Aug 2026 · 11:00 AM SGT' },
      { label: 'Mentor', value: 'Priya Nair · Senior Data Scientist' },
      { label: 'Reason', value: 'University assessment at the original time' },
    ],
  },
  'applicant-offer-detail': {
    id: 'applicant-offer-detail', eyebrow: 'Offer · Response required',
    title: 'Your internship offer',
    description: 'Review the placement, internship period and offer documents before making your decision.',
    status: 'Respond by 5 Sep 2026', statusTone: 'warning', activeRoute: '/apply/offers',
    backLabel: 'My Offers', backRoute: '/apply/offers',
    primaryLabel: 'Accept Offer', primaryRoute: '/apply/applicant-offer-review?decision=accept',
    secondaryLabel: 'Reject Offer', secondaryRoute: '/apply/applicant-offer-reject',
    notice: 'Your response must be submitted by 5 Sep 2026 at 11:59 PM SGT.',
    details: [
      { label: 'Programme', value: 'Undergraduate Internship 2027' },
      { label: 'Project', value: 'AI Threat Detection' },
      { label: 'Internship period', value: '14 Sep – 11 Dec 2026' },
      { label: 'Work arrangement', value: 'Hybrid · DSTA Digital Hub' },
      { label: 'Mentor', value: 'Aisha Rahman' },
      { label: 'Allowance', value: 'S$1,500 per month' },
    ],
    checklist: ['Review internship dates', 'Review reporting location', 'Read the internship offer letter'],
  },
  'applicant-offer-review': {
    id: 'applicant-offer-review', eyebrow: 'Offer · Accept',
    title: 'Review your acceptance',
    description: 'Confirm that you understand the key offer details before accepting your internship placement.',
    status: 'Final review', statusTone: 'warning', activeRoute: '/apply/offers',
    backLabel: 'Internship offer', backRoute: '/apply/applicant-offer-detail',
    primaryLabel: 'Confirm Acceptance', primaryRoute: '/apply/applicant-offer-confirmation?decision=accepted',
    secondaryLabel: 'Back to Offer', secondaryRoute: '/apply/applicant-offer-detail',
    notice: 'By accepting, you confirm your availability for the internship period and agree to complete onboarding.',
    details: [
      { label: 'Decision', value: 'Accept offer' },
      { label: 'Programme', value: 'Undergraduate Internship 2027' },
      { label: 'Project', value: 'AI Threat Detection' },
      { label: 'Internship period', value: '14 Sep – 11 Dec 2026' },
    ],
    checklist: ['I have reviewed the offer letter', 'I am available for the full internship period'],
  },
  'applicant-offer-reject': {
    id: 'applicant-offer-reject', eyebrow: 'Offer · Reject',
    title: 'Tell us about your decision',
    description: 'Your feedback helps the internship team understand your decision. Remarks are optional.',
    status: 'Offer open', statusTone: 'warning', activeRoute: '/apply/offers',
    backLabel: 'Internship offer', backRoute: '/apply/applicant-offer-detail',
    primaryLabel: 'Confirm Rejection', primaryRoute: '/apply/applicant-offer-confirmation?decision=rejected',
    secondaryLabel: 'Keep Offer', secondaryRoute: '/apply/applicant-offer-detail',
    notice: 'Rejecting the offer will close this application. Review your decision before submitting.',
    details: [
      { label: 'Programme', value: 'Undergraduate Internship 2027' },
      { label: 'Response deadline', value: '5 Sep 2026 · 11:59 PM SGT' },
    ],
  },
  'applicant-offer-confirmation': {
    id: 'applicant-offer-confirmation', eyebrow: 'Offer · Response submitted',
    title: 'Your offer response is recorded',
    description: 'Your application status has been updated. The next step depends on the decision you submitted.',
    status: 'Submitted', statusTone: 'success', activeRoute: '/apply/offers',
    backLabel: 'My Offers', backRoute: '/apply/offers',
    primaryLabel: 'Continue to Onboarding', primaryRoute: '/apply/onboarding',
    secondaryLabel: 'View Application', secondaryRoute: '/apply/applications/app-ui-2027',
    details: [
      { label: 'Programme', value: 'Undergraduate Internship 2027' },
      { label: 'Submitted', value: '21 Aug 2026 · 11:06 AM SGT' },
      { label: 'Application ID', value: 'APP-UI27-00184' },
    ],
  },
  'applicant-onboarding-requirement': {
    id: 'applicant-onboarding-requirement', eyebrow: 'Onboarding · Requirement',
    title: 'Emergency contact and declarations',
    description: 'Complete this requirement so the internship team can prepare for your first day.',
    status: 'Action required', statusTone: 'warning', activeRoute: '/apply/internship',
    backLabel: 'Onboarding requirements', backRoute: '/apply/onboarding',
    primaryLabel: 'Review Submission', primaryRoute: '/apply/applicant-onboarding-review',
    secondaryLabel: 'Save and Exit', secondaryRoute: '/apply/onboarding',
    details: [
      { label: 'Requirement', value: 'Emergency contact and declarations' },
      { label: 'Due', value: '15 Sep 2026' },
      { label: 'Status', value: 'Not started' },
    ],
  },
  'applicant-onboarding-review': {
    id: 'applicant-onboarding-review', eyebrow: 'Onboarding · Review',
    title: 'Review your onboarding information',
    description: 'Check the information and acknowledgements before submitting them to the internship team.',
    status: 'Review required', statusTone: 'warning', activeRoute: '/apply/internship',
    backLabel: 'Edit requirement', backRoute: '/apply/applicant-onboarding-requirement',
    primaryLabel: 'Submit Requirement', primaryRoute: '/apply/applicant-onboarding-confirmation',
    secondaryLabel: 'Edit Information', secondaryRoute: '/apply/applicant-onboarding-requirement',
    notice: 'You can update submitted information later if the internship team requests a change.',
    details: [
      { label: 'Emergency contact', value: 'Daniel Aw · Parent' },
      { label: 'Mobile number', value: '+65 9123 4567' },
      { label: 'Declarations', value: 'IT policy and PDPA acknowledged' },
    ],
  },
  'applicant-onboarding-confirmation': {
    id: 'applicant-onboarding-confirmation', eyebrow: 'Onboarding · Submitted',
    title: 'Requirement submitted',
    description: 'Your information has been sent to the internship team and your onboarding progress has been updated.',
    status: 'Completed', statusTone: 'success', activeRoute: '/apply/internship',
    backLabel: 'Onboarding', backRoute: '/apply/onboarding',
    primaryLabel: 'Return to Onboarding', primaryRoute: '/apply/onboarding',
    secondaryLabel: 'View Internship', secondaryRoute: '/apply/internship',
    notice: 'Two onboarding requirements remain. Complete them by 15 Sep 2026.',
    details: [
      { label: 'Submitted requirement', value: 'Emergency contact and declarations' },
      { label: 'Submitted', value: '21 Aug 2026 · 11:18 AM SGT' },
      { label: 'Overall progress', value: '1 of 3 requirements completed' },
    ],
  },
  'applicant-offboarding': {
    id: 'applicant-offboarding', eyebrow: 'Internship · Completion',
    title: 'Complete your internship journey',
    description: 'Finish required offboarding and explore optional ways to keep a record of your experience.',
    status: '1 required action', statusTone: 'warning', activeRoute: '/apply/internship',
    backLabel: 'My Internship', backRoute: '/apply/internship',
    primaryLabel: 'Start Feedback', primaryRoute: '/apply/feedback/APP-0031',
    secondaryLabel: 'View Certificate Status', secondaryRoute: '/apply/certification',
    notice: 'Internship feedback must be submitted before your certificate can be generated.',
    details: [
      { label: 'Internship', value: 'University Internship 2026' },
      { label: 'Project', value: 'Cybersecurity Threat Analysis' },
      { label: 'Completion date', value: '19 Sep 2026' },
      { label: 'Mentor', value: 'Wei Jian Lim' },
    ],
    checklist: ['Submit internship feedback · Required', 'Request a testimonial · Optional', 'Share your experience · Optional'],
  },
  'applicant-feedback-review': {
    id: 'applicant-feedback-review', eyebrow: 'Offboarding · Feedback review',
    title: 'Review your internship feedback',
    description: 'Check your ratings and written feedback before final submission.',
    status: 'Final review', statusTone: 'warning', activeRoute: '/apply/internship',
    backLabel: 'Edit feedback', backRoute: '/apply/feedback/APP-0031',
    primaryLabel: 'Submit Feedback', primaryRoute: '/apply/applicant-feedback-confirmation',
    secondaryLabel: 'Edit Responses', secondaryRoute: '/apply/feedback/APP-0031',
    notice: 'Submitted feedback cannot be edited in this prototype.',
    details: [
      { label: 'Overall experience', value: '5 of 5' },
      { label: 'Project difficulty', value: 'Just right' },
      { label: 'Recommend DSTA', value: '9 of 10' },
      { label: 'Mentor message', value: 'Thank you for the guidance and regular feedback.' },
    ],
  },
  'applicant-feedback-confirmation': {
    id: 'applicant-feedback-confirmation', eyebrow: 'Offboarding · Feedback submitted',
    title: 'Thank you for your feedback',
    description: 'Your feedback has been received and the required offboarding action is complete.',
    status: 'Completed', statusTone: 'success', activeRoute: '/apply/internship',
    backLabel: 'Offboarding', backRoute: '/apply/applicant-offboarding',
    primaryLabel: 'Return to Offboarding', primaryRoute: '/apply/applicant-offboarding',
    secondaryLabel: 'View Certificate Status', secondaryRoute: '/apply/certification',
    notice: 'Your certificate will be available after final internship clearance.',
    details: [
      { label: 'Submitted', value: '21 Aug 2026 · 11:35 AM SGT' },
      { label: 'Offboarding progress', value: 'Required actions completed' },
      { label: 'Certificate', value: 'Pending final clearance' },
    ],
  },
  'applicant-testimonial-request': {
    id: 'applicant-testimonial-request', eyebrow: 'Internship · Testimonial',
    title: 'Request a testimonial',
    description: 'Let your mentor know how you plan to use the testimonial and what you would like it to highlight.',
    status: 'Optional', statusTone: 'subtle', activeRoute: '/apply/internship',
    backLabel: 'Offboarding', backRoute: '/apply/applicant-offboarding',
    primaryLabel: 'Submit Request', primaryRoute: '/apply/applicant-testimonial-status',
    secondaryLabel: 'Not Now', secondaryRoute: '/apply/applicant-offboarding',
    details: [
      { label: 'Mentor', value: 'Wei Jian Lim · Senior Research Scientist' },
      { label: 'Internship', value: 'University Internship 2026' },
      { label: 'Project', value: 'Cybersecurity Threat Analysis' },
    ],
  },
  'applicant-testimonial-status': {
    id: 'applicant-testimonial-status', eyebrow: 'Internship · Testimonial request',
    title: 'Your request is with your mentor',
    description: 'We will notify you when the testimonial is available or if your mentor needs more information.',
    status: 'Under mentor review', statusTone: 'info', activeRoute: '/apply/internship',
    backLabel: 'My Internship', backRoute: '/apply/internship',
    primaryLabel: 'Return to Internship', primaryRoute: '/apply/internship',
    secondaryLabel: 'View Offboarding', secondaryRoute: '/apply/applicant-offboarding',
    notice: 'No action is needed while the request is under review.',
    details: [
      { label: 'Requested', value: '21 Aug 2026' },
      { label: 'Mentor', value: 'Wei Jian Lim' },
      { label: 'Status', value: 'Under mentor review' },
      { label: 'Typical response', value: 'Within 10 working days' },
    ],
  },
  'applicant-linkedin-share': {
    id: 'applicant-linkedin-share', eyebrow: 'Internship · Share experience',
    title: 'Share your experience on LinkedIn',
    description: 'Review and edit the suggested content before continuing to LinkedIn.',
    status: 'Optional', statusTone: 'subtle', activeRoute: '/apply/internship',
    backLabel: 'Offboarding', backRoute: '/apply/applicant-offboarding',
    primaryLabel: 'Continue to LinkedIn', primaryRoute: '/apply/applicant-offboarding?shared=linkedin',
    secondaryLabel: 'Cancel', secondaryRoute: '/apply/applicant-offboarding',
    notice: 'You will leave TOA. Nothing will be published automatically.',
    details: [
      { label: 'Internship', value: 'University Internship 2026' },
      { label: 'Project', value: 'Cybersecurity Threat Analysis' },
      { label: 'Organisation', value: 'Defence Science and Technology Agency' },
    ],
  },
  'applicant-certificate-viewer': {
    id: 'applicant-certificate-viewer', eyebrow: 'Internship · Certificate',
    title: 'Internship Certificate of Completion',
    description: 'Review your certificate details and download a copy for your records.',
    status: 'Available', statusTone: 'success', activeRoute: '/apply/certification',
    backLabel: 'Certification', backRoute: '/apply/certification',
    primaryLabel: 'Download PDF', primaryRoute: '/apply/certification?downloaded=true',
    secondaryLabel: 'Return to Internship', secondaryRoute: '/apply/internship',
    details: [
      { label: 'Applicant', value: 'Jenny Aw' },
      { label: 'Internship', value: 'University Internship 2026' },
      { label: 'Project', value: 'Cybersecurity Threat Analysis' },
      { label: 'Internship period', value: '23 Jun – 19 Sep 2026' },
      { label: 'Certificate ID', value: 'DSTA-INT-2026-00418' },
      { label: 'Issued', value: '21 Sep 2026' },
    ],
  },
};
