import type {
  ApplicantDashboardState,
  ApplicantDashboardStateConfig,
  ApplicantHomeScenario,
} from '@/lib/types';

export const APPLICANT_DASHBOARD_STATE_TO_SCENARIO: Record<ApplicantDashboardState, ApplicantHomeScenario> = {
  multiple_active_applications: 'multiple-applications',
  no_active_application: 'no-application',
  draft_application: 'draft-application',
  application_submitted: 'submitted',
  application_under_review: 'under-review',
  interview_invitation: 'interview-action',
  interview_pending_confirmation: 'interview-pending-confirmation',
  interview_confirmed: 'interview-scheduled',
  interview_rescheduling: 'interview-rescheduling',
  offer_received: 'offer-action',
  onboarding: 'onboarding-action',
  application_unsuccessful: 'application-unsuccessful',
  application_withdrawn: 'application-withdrawn',
  offer_declined: 'offer-declined',
  offer_expired: 'offer-expired',
  internship_in_progress: 'active-internship',
  offboarding_required: 'completion-action',
  internship_completed: 'journey-completed',
};

export const APPLICANT_HOME_SCENARIO_TO_STATE: Record<ApplicantHomeScenario, ApplicantDashboardState> = {
  'multiple-applications': 'multiple_active_applications',
  'no-application': 'no_active_application',
  'draft-application': 'draft_application',
  submitted: 'application_submitted',
  'under-review': 'application_under_review',
  'interview-action': 'interview_invitation',
  'interview-pending-confirmation': 'interview_pending_confirmation',
  'interview-scheduled': 'interview_confirmed',
  'interview-rescheduling': 'interview_rescheduling',
  'interview-completed': 'interview_pending_confirmation',
  'offer-action': 'offer_received',
  'onboarding-action': 'onboarding',
  'application-unsuccessful': 'application_unsuccessful',
  'application-withdrawn': 'application_withdrawn',
  'offer-declined': 'offer_declined',
  'offer-expired': 'offer_expired',
  'active-internship': 'internship_in_progress',
  'completion-action': 'offboarding_required',
  'journey-completed': 'internship_completed',
};

const shared = {
  programme: 'University Internship 2027',
  reference: 'APP-UI27-00418',
  role: 'Software Engineering Intern',
  period: '2 Jun - 31 Jul 2027',
  location: 'DSTA HQ, Singapore',
} as const;

// One canonical chronology keeps repeated milestones consistent across every
// dashboard state and makes the alternative outcome paths easy to compare.
const activityTime = {
  personalDetailsCompleted: '28 Aug 2026, 3:45 PM',
  draftSaved: '28 Aug 2026, 4:20 PM',
  draftCompleted: '30 Aug 2026, 3:55 PM',
  applicationSubmitted: '30 Aug 2026, 4:00 PM',
  reviewStarted: '31 Aug 2026, 9:30 AM',
  applicationShortlisted: '1 Sep 2026, 9:45 AM',
  interviewInvitationReceived: '1 Sep 2026, 10:30 AM',
  interviewAvailabilitySubmitted: '1 Sep 2026, 2:10 PM',
  interviewConfirmed: '2 Sep 2026, 11:00 AM',
  interviewRescheduleRequested: '3 Sep 2026, 1:20 PM',
  interviewCompleted: '4 Sep 2026, 3:00 PM',
  offerReceived: '5 Sep 2026, 11:00 AM',
  offerAccepted: '6 Sep 2026, 9:00 AM',
  onboardingStarted: '6 Sep 2026, 9:15 AM',
  internshipStarted: '2 Jun 2027, 9:00 AM',
  mentorAssigned: '26 May 2027, 10:00 AM',
  onboardingCompleted: '28 May 2027, 4:00 PM',
  completionChecklistAssigned: '15 Jul 2027, 9:00 AM',
  offboardingCompleted: '31 Jul 2027, 4:00 PM',
  internshipCompleted: '31 Jul 2027, 5:00 PM',
  certificateAvailable: '1 Aug 2027, 9:00 AM',
} as const;

export const APPLICANT_DASHBOARD_STATES: Record<
  Exclude<ApplicantDashboardState, 'no_active_application' | 'multiple_active_applications'>,
  ApplicantDashboardStateConfig
> = {
  draft_application: {
    state: 'draft_application', pattern: 'action',
    heroLines: ['Continue your', 'application'],
    heroCopy: 'Your application is in progress. Pick up where you left off and complete the remaining sections.',
    badge: 'Application in progress',
    spotlightTitle: 'Resume your application',
    spotlightCopy: 'Complete the remaining sections and review everything before you submit.',
    metadata: [
      { label: 'Programme', value: shared.programme },
      { label: 'Status', value: 'Draft' },
      { label: 'Last updated', value: '28 Aug 2026' },
    ],
    dueText: 'Applications close 30 Sep 2026',
    primaryAction: { label: 'Resume Application', route: '/apply/review' },
    secondaryAction: { label: 'View Programme', route: '/join-us/student/internships' },
    journeyStage: 'application', journeyStageHint: 'Draft · Not submitted', completedStages: [], journeyTitle: 'Complete your application',
    journeyItems: ['Complete personal details', 'Add education details', 'Upload supporting documents', 'Review and submit'],
    guideTitle: 'Application Guide',
    guideItems: ['Check required information', 'Prepare documents before submission', 'Review your application carefully'],
    guideActionLabel: 'View Application Guide',
    activity: [{ title: 'Draft application saved', date: activityTime.draftSaved }, { title: 'Personal details completed', date: activityTime.personalDetailsCompleted }],
  },
  application_submitted: {
    state: 'application_submitted', pattern: 'waiting',
    heroLines: ['Application', 'submitted'],
    heroCopy: 'Your application has been received successfully. We’ll let you know when the review begins or if any action is required.',
    badge: 'Submitted',
    spotlightTitle: 'You’re all caught up',
    spotlightCopy: 'Nothing is required from you right now. We’ll notify you when there’s an update.',
    metadata: [
      { label: 'Programme', value: shared.programme },
      { label: 'Submitted', value: '30 Aug 2026' },
      { label: 'Application reference', value: shared.reference },
    ],
    primaryAction: null,
    secondaryAction: { label: 'View Application', route: '/apply/applications' },
    journeyStage: 'application', completedStages: ['application'], journeyTitle: 'What happens next',
    journeyItems: ['Application review', 'Potential interview', 'Status updates'],
    guideTitle: 'What to expect after submission',
    guideItems: ['Keep your contact details current', 'Monitor notifications', 'Prepare for a possible interview'],
    guideActionLabel: 'View Guide',
    activity: [{ title: 'Application submitted', date: activityTime.applicationSubmitted }, { title: 'Draft application completed', date: activityTime.draftCompleted }],
  },
  application_under_review: {
    state: 'application_under_review', pattern: 'waiting',
    heroLines: ['Your application is', 'under review'],
    heroCopy: 'Your application is currently with our review team. We’ll keep you updated on what happens next and any expected timelines.',
    badge: 'Under review',
    spotlightTitle: 'Nothing is required from you right now',
    spotlightCopy: 'We’ll let you know if we need anything else.',
    spotlightImage: '/images/applicant-dashboard-application-under-review.png',
    metadata: [
      { label: 'Programme', value: shared.programme },
      { label: 'Current status', value: 'Under review' },
      { label: 'Application reference', value: shared.reference },
    ],
    primaryAction: null,
    secondaryAction: { label: 'View Application', route: '/apply/applications' },
    journeyStage: 'review', completedStages: ['application'], journeyTitle: 'What happens next',
    journeyItems: ['Application assessment', 'Shortlisting decision', 'Interview invitation, if shortlisted'],
    guideTitle: 'While your application is being reviewed',
    guideItems: ['Keep your contact details current', 'Check notifications', 'Prepare for a potential interview'],
    activity: [{ title: 'Application review started', date: activityTime.reviewStarted }, { title: 'Application submitted', date: activityTime.applicationSubmitted }],
  },
  interview_invitation: {
    state: 'interview_invitation', pattern: 'action',
    heroLines: ['You’ve been invited', 'to an interview'],
    heroCopy: 'Please select your preferred interview timeslots by 3 Sep 2026.',
    badge: 'Action required',
    spotlightTitle: 'Choose your interview availability',
    spotlightCopy: 'Select your preferred timeslots. We’ll confirm your interview after reviewing your availability.',
    spotlightImage: '/images/applicant-dashboard-interview-invitation.png',
    metadata: [{ label: 'Programme', value: shared.programme }, { label: 'Stage', value: 'Interview' }],
    dueText: 'Due 3 Sep 2026',
    primaryAction: { label: 'Select Timeslots', route: '/apply/interviews' },
    secondaryAction: { label: 'View Application', route: '/apply/applications' },
    journeyStage: 'interview', completedStages: ['application', 'review'], journeyTitle: 'What happens next',
    journeyItems: ['Submit availability', 'Interview confirmation', 'Interview details shared'],
    guideTitle: 'Interview Guide',
    guideItems: ['Prepare your availability', 'Check your contact details', 'Review what to expect in the interview process'],
    guideActionLabel: 'View Guide',
    activity: [{ title: 'Interview invitation received', date: activityTime.interviewInvitationReceived }, { title: 'Application shortlisted', date: activityTime.applicationShortlisted }, { title: 'Application review started', date: activityTime.reviewStarted }],
  },
  interview_pending_confirmation: {
    state: 'interview_pending_confirmation', pattern: 'waiting',
    heroLines: ['Interview availability', 'submitted'],
    heroCopy: 'We’re confirming your interview schedule. We’ll notify you once the time is finalised.',
    badge: 'Pending confirmation',
    spotlightTitle: 'You’re all caught up',
    spotlightCopy: 'No further action is required right now.',
    spotlightImage: '/images/applicant-dashboard-interview-pending-confirmation.png',
    metadata: [
      { label: 'Programme', value: shared.programme },
      { label: 'Selected availability', value: '3 Sep, 2:00-4:00 PM' },
      { label: 'Alternative availability', value: '4 Sep, 10:00 AM-12:00 PM' },
    ],
    primaryAction: null,
    secondaryAction: { label: 'View Availability', route: '/apply/applications/app-ui-2027' },
    journeyStage: 'interview', completedStages: ['application', 'review'], journeyTitle: 'What happens next',
    journeyItems: ['We review your availability', 'Interview time is confirmed', 'Meeting details are shared'],
    guideTitle: 'Interview Guide',
    guideItems: ['Prepare while waiting for confirmation', 'Check your email and notifications', 'Keep your calendar available'],
    activity: [{ title: 'Interview availability submitted', date: activityTime.interviewAvailabilitySubmitted }, { title: 'Interview invitation received', date: activityTime.interviewInvitationReceived }],
  },
  interview_confirmed: {
    state: 'interview_confirmed', pattern: 'progress',
    heroLines: ['Your interview is', 'confirmed'],
    heroCopy: 'Your interview is scheduled. Review the details below and get ready for the session.',
    badge: 'Interview confirmed',
    spotlightTitle: 'Upcoming interview',
    spotlightCopy: 'Review your meeting details and prepare before the session.',
    spotlightImage: '/images/applicant-dashboard-interview-confirmed.png',
    metadata: [
      { label: 'Programme', value: shared.programme }, { label: 'Interview date', value: '3 Sep 2026' },
      { label: 'Time', value: '2:00 PM' }, { label: 'Format', value: 'Online interview' },
    ],
    primaryAction: { label: 'View Interview Details', route: '/apply/applications/app-ui-2027' },
    secondaryAction: { label: 'Add to Calendar', route: null },
    journeyStage: 'interview', completedStages: ['application', 'review'], journeyTitle: 'What happens next',
    journeyItems: ['Attend interview', 'Interview outcome review', 'Offer decision, if successful'],
    guideTitle: 'Interview Preparation Guide',
    guideItems: ['Review the interview format', 'Prepare relevant examples and projects', 'Check your meeting link and device', 'Join early'],
    guideActionLabel: 'View Guide',
    activity: [{ title: 'Interview schedule confirmed', date: activityTime.interviewConfirmed }, { title: 'Interview availability submitted', date: activityTime.interviewAvailabilitySubmitted }],
  },
  interview_rescheduling: {
    state: 'interview_rescheduling', pattern: 'action',
    heroLines: ['Your interview needs', 'to be rescheduled'],
    heroCopy: 'Please provide new availability so we can confirm another interview time.',
    badge: 'Action required',
    spotlightTitle: 'Update your interview availability',
    spotlightCopy: 'Choose multiple suitable times so we can confirm a new interview quickly.',
    spotlightImage: '/images/applicant-dashboard-interview-rescheduling.png',
    metadata: [{ label: 'Programme', value: shared.programme }, { label: 'Previous interview', value: '3 Sep 2026, 2:00 PM' }],
    dueText: 'Due 5 Sep 2026',
    primaryAction: { label: 'Update Availability', route: '/apply/interview-proposed' },
    secondaryAction: { label: 'View Previous Details', route: '/apply/applications/app-ui-2027' },
    journeyStage: 'interview', completedStages: ['application', 'review'], journeyTitle: 'What happens next',
    journeyItems: ['Submit new availability', 'We confirm a new time', 'Updated interview details are shared'],
    guideTitle: 'Rescheduling Guide',
    guideItems: ['Check your calendar', 'Provide multiple suitable timeslots', 'Keep your contact details current'],
    activity: [{ title: 'Interview reschedule requested', date: activityTime.interviewRescheduleRequested }, { title: 'Original interview confirmed', date: activityTime.interviewConfirmed }],
  },
  offer_received: {
    state: 'offer_received', pattern: 'action',
    heroLines: ['You’ve received', 'an offer!'],
    heroCopy: 'Congratulations! You’ve been offered a place in the University Internship 2027 programme.',
    badge: 'Action required',
    spotlightTitle: 'Review your offer and let us know your decision',
    spotlightCopy: 'Review the offer letter, internship details and terms before responding.',
    spotlightImage: '/images/applicant-dashboard-offer-received.png',
    metadata: [
      { label: 'Programme', value: shared.programme }, { label: 'Role', value: shared.role },
      { label: 'Internship period', value: shared.period }, { label: 'Location', value: shared.location },
    ],
    dueText: 'Respond by 10 Sep 2026',
    primaryAction: { label: 'Review Offer', route: '/apply/applicant-offer-detail?applicationId=app-ui-2027' },
    secondaryAction: { label: 'View Details', route: '/apply/applications/app-ui-2027' },
    journeyStage: 'offer', completedStages: ['application', 'review', 'interview'], journeyTitle: 'What happens next',
    journeyItems: ['Review your offer', 'Accept or decline your offer', 'Complete onboarding after acceptance'],
    guideTitle: 'Offer Guide',
    guideItems: ['Review the offer letter and attachments', 'Understand the terms and conditions', 'Understand what happens after acceptance'],
    guideActionLabel: 'View Offer Guide',
    activity: [{ title: 'Internship offer received', date: activityTime.offerReceived }, { title: 'Interview completed', date: activityTime.interviewCompleted }],
  },
  onboarding: {
    state: 'onboarding', pattern: 'progress',
    heroLines: ['Complete your onboarding', 'to get started'],
    heroCopy: 'Congratulations on accepting the offer. Complete the remaining onboarding tasks so we can prepare for your internship.',
    badge: 'Action required',
    spotlightTitle: 'Verify your personal details',
    spotlightCopy: 'This is the next required onboarding task.',
    spotlightImage: '/images/applicant-dashboard-onboarding.png',
    metadata: [
      { label: 'Programme', value: shared.programme }, { label: 'Role', value: shared.role },
      { label: 'Internship period', value: shared.period }, { label: 'Location', value: shared.location },
    ],
    progressText: '60% complete, 3 of 5 tasks', dueText: 'Due 25 May 2027',
    primaryAction: { label: 'Continue Checklist', route: '/apply/applicant-onboarding-requirement' },
    secondaryAction: { label: 'View Details', route: '/apply/internship' },
    journeyStage: 'onboarding', completedStages: ['application', 'review', 'interview', 'offer'], journeyTitle: 'Onboarding checklist',
    journeyItems: ['Personal details', 'Required documents', 'Policies and declarations', 'Pre-internship briefing', 'Team and project information'],
    guideTitle: 'Onboarding Guide',
    guideItems: ['Complete personal details', 'Submit required documents', 'Read and acknowledge policies', 'Attend the pre-internship briefing'],
    guideActionLabel: 'View Onboarding Guide',
    activity: [{ title: 'Onboarding started', date: activityTime.onboardingStarted }, { title: 'Internship offer accepted', date: activityTime.offerAccepted }, { title: 'Internship offer received', date: activityTime.offerReceived }],
  },
  application_unsuccessful: {
    state: 'application_unsuccessful', pattern: 'closed',
    heroLines: ['Your application', 'has concluded'],
    heroCopy: 'Thank you for your interest. Your application was not selected to progress beyond the review stage for this intake.',
    badge: 'Unsuccessful',
    spotlightTitle: 'Application outcome available',
    spotlightCopy: 'This application is closed, but its details and outcome remain available for your records.',
    metadata: [
      { label: 'Programme', value: shared.programme },
      { label: 'Outcome', value: 'Unsuccessful' },
      { label: 'Application reference', value: shared.reference },
    ],
    primaryAction: null,
    secondaryAction: { label: 'View Application', route: '/apply/applications/app-ui-2026' },
    journeyStage: 'interview', completedStages: ['application', 'review'],
    terminalStage: 'interview', terminalLabel: 'Unsuccessful',
    journeyTitle: 'Application concluded after review',
    journeyItems: ['Application submitted - Completed', 'Application review - Completed', 'Application unsuccessful'],
    guideTitle: 'Your application record',
    guideItems: ['Review the application outcome', 'Keep your profile current', 'Explore other internship opportunities'],
    activity: [{ title: 'Application outcome: Unsuccessful', date: '1 Sep 2026, 10:00 AM' }, { title: 'Application review completed', date: '1 Sep 2026, 9:50 AM' }, { title: 'Application review started', date: activityTime.reviewStarted }],
  },
  application_withdrawn: {
    state: 'application_withdrawn', pattern: 'closed',
    heroLines: ['Your application', 'was withdrawn'],
    heroCopy: 'You withdrew this application before it progressed to the review stage.',
    badge: 'Withdrawn',
    spotlightTitle: 'Application withdrawn',
    spotlightCopy: 'No further action is required. The submitted application remains available as a read-only record.',
    metadata: [
      { label: 'Programme', value: 'Tech UP Internship 2026' },
      { label: 'Withdrawn from', value: 'Submitted' },
      { label: 'Status', value: 'Withdrawn' },
    ],
    primaryAction: null,
    secondaryAction: { label: 'View Application', route: '/apply/applications/app-techup-2026' },
    journeyStage: 'review', completedStages: ['application'],
    terminalStage: 'review', terminalLabel: 'Withdrawn',
    journeyTitle: 'Application withdrawn after submission',
    journeyItems: ['Application submitted - Completed', 'Application withdrawn'],
    guideTitle: 'Your application record',
    guideItems: ['Review the withdrawn application', 'Keep your profile current', 'Start a new application when ready'],
    activity: [{ title: 'Application withdrawn', date: '31 Aug 2026, 10:00 AM' }, { title: 'Application submitted', date: activityTime.applicationSubmitted }],
  },
  offer_declined: {
    state: 'offer_declined', pattern: 'closed',
    heroLines: ['Your offer', 'was declined'],
    heroCopy: 'You declined this internship offer. The application and offer remain available for your records.',
    badge: 'Offer declined',
    spotlightTitle: 'Offer response recorded',
    spotlightCopy: 'Your decision has been submitted and this application is now closed.',
    metadata: [
      { label: 'Programme', value: shared.programme },
      { label: 'Outcome', value: 'Offer declined' },
      { label: 'Role', value: shared.role },
    ],
    primaryAction: null,
    secondaryAction: { label: 'View Application', route: '/apply/applications' },
    journeyStage: 'offer', completedStages: ['application', 'review', 'interview'],
    terminalStage: 'offer', terminalLabel: 'Offer declined',
    journeyTitle: 'Offer decision recorded',
    journeyItems: ['Application and interview - Completed', 'Offer received - Completed', 'Offer declined'],
    guideTitle: 'Your offer record',
    guideItems: ['Review your submitted decision', 'Keep a copy of relevant documents', 'Explore other internship opportunities'],
    activity: [{ title: 'Internship offer declined', date: activityTime.offerAccepted }, { title: 'Internship offer received', date: activityTime.offerReceived }],
  },
  offer_expired: {
    state: 'offer_expired', pattern: 'closed',
    heroLines: ['Your offer', 'has expired'],
    heroCopy: 'The response deadline passed before a decision was submitted. This application is now closed.',
    badge: 'Offer expired',
    spotlightTitle: 'Offer response period ended',
    spotlightCopy: 'The expired offer and application details remain available for your records.',
    metadata: [
      { label: 'Programme', value: shared.programme },
      { label: 'Outcome', value: 'Offer expired' },
      { label: 'Response deadline', value: '10 Sep 2026' },
    ],
    primaryAction: null,
    secondaryAction: { label: 'View Application', route: '/apply/applications' },
    journeyStage: 'offer', completedStages: ['application', 'review', 'interview'],
    terminalStage: 'offer', terminalLabel: 'Offer expired',
    journeyTitle: 'Offer response period ended',
    journeyItems: ['Application and interview - Completed', 'Offer received - Completed', 'Offer expired'],
    guideTitle: 'Your offer record',
    guideItems: ['Review the expired offer', 'Keep your profile current', 'Explore other internship opportunities'],
    activity: [{ title: 'Internship offer expired', date: '10 Sep 2026, 11:59 PM' }, { title: 'Internship offer received', date: activityTime.offerReceived }],
  },
  internship_in_progress: {
    state: 'internship_in_progress', pattern: 'progress',
    heroLines: ['Your internship', 'at DSTA'],
    heroCopy: 'Your internship is in progress. Keep track of key dates, tasks and updates here.',
    badge: 'Internship in progress',
    spotlightTitle: 'Your current internship',
    spotlightCopy: 'Stay on top of your next milestone and use this dashboard as your internship home.',
    spotlightImage: '/images/applicant-dashboard-internship-in-progress.png',
    metadata: [
      { label: 'Programme', value: shared.programme }, { label: 'Role', value: shared.role },
      { label: 'Mentor', value: 'Marcus Tan' }, { label: 'Internship period', value: shared.period },
      { label: 'Location', value: shared.location }, { label: 'Next milestone', value: 'Midpoint check-in, 30 Jun 2027' },
    ],
    primaryAction: { label: 'View Internship Details', route: '/apply/internship' },
    secondaryAction: null,
    journeyStage: 'internship', completedStages: ['application', 'review', 'interview', 'offer', 'onboarding'], journeyTitle: 'Current internship milestones',
    journeyItems: ['Internship started - Completed', 'Midpoint check-in', 'Final review', 'Offboarding and completion'],
    guideTitle: 'Internship Guide and Resources',
    guideItems: ['Key contacts', 'Internship expectations', 'Resources and support', 'Important policies'],
    activity: [{ title: 'Internship started', date: activityTime.internshipStarted }, { title: 'Onboarding completed', date: activityTime.onboardingCompleted }, { title: 'Mentor assigned', date: activityTime.mentorAssigned }],
  },
  offboarding_required: {
    state: 'offboarding_required', pattern: 'progress',
    heroLines: ['Complete your', 'offboarding checklist'],
    heroCopy: 'You’re near the finish line. Please complete the remaining items before your internship ends.',
    badge: 'Action required',
    spotlightTitle: 'Continue your completion checklist',
    spotlightCopy: 'Three items still need your attention before your internship ends.',
    spotlightImage: '/images/applicant-dashboard-offboarding-required.png',
    metadata: [
      { label: 'Programme', value: shared.programme }, { label: 'Status', value: 'Offboarding in progress' },
      { label: 'Internship period', value: shared.period }, { label: 'Internship ends', value: '31 Jul 2027' },
    ],
    progressText: '40% complete, 2 of 5 items',
    primaryAction: { label: 'Continue Checklist', route: '/apply/applicant-offboarding' },
    secondaryAction: { label: 'View Details', route: '/apply/internship' },
    journeyStage: 'completion', completedStages: ['application', 'review', 'interview', 'offer', 'onboarding', 'internship'], journeyTitle: 'Offboarding checklist',
    journeyItems: ['Exit interview - Completed', 'Project handover - Completed', 'Return DSTA assets - Pending', 'Final timesheet submission - Pending', 'Completion survey - Pending'],
    guideTitle: 'Completion Guide',
    guideItems: ['Review offboarding requirements', 'Complete all checklist items', 'Return company assets on time', 'Keep a copy of important documents'],
    guideActionLabel: 'View Completion Guide',
    activity: [{ title: 'Completion checklist assigned', date: activityTime.completionChecklistAssigned }, { title: 'Internship started', date: activityTime.internshipStarted }],
  },
  internship_completed: {
    state: 'internship_completed', pattern: 'completed',
    heroLines: ['Congratulations on completing', 'your internship'],
    heroCopy: 'Thank you for your contribution to DSTA. Your internship journey is now complete.',
    badge: 'Completed',
    spotlightTitle: 'Your internship is complete',
    spotlightCopy: 'Your completed record and post-internship resources are available here.',
    spotlightImage: '/images/applicant-dashboard-internship-completed.png',
    metadata: [
      { label: 'Programme', value: shared.programme }, { label: 'Status', value: 'Internship completed' },
      { label: 'Internship period', value: shared.period }, { label: 'Completed', value: '31 Jul 2027' },
    ],
    primaryAction: null,
    secondaryAction: { label: 'View Internship Summary', route: '/apply/internship' },
    journeyStage: 'completion', completedStages: ['application', 'review', 'interview', 'offer', 'onboarding', 'internship', 'completion'], journeyTitle: 'After your internship',
    journeyItems: [],
    guideTitle: 'After Your Internship Guide',
    guideItems: ['Access your certificate', 'Complete any outstanding feedback', 'Submit or review your testimonial', 'Share your experience on LinkedIn (optional)'],
    activity: [{ title: 'Certificate available', date: activityTime.certificateAvailable }, { title: 'Internship completed', date: activityTime.internshipCompleted }, { title: 'Offboarding completed', date: activityTime.offboardingCompleted }],
    postInternshipItems: [
      { title: 'Feedback', status: 'Completed', action: 'View', route: '/apply/internship' },
      { title: 'Testimonial', status: 'Ready to submit', action: 'Submit', route: '/apply/applicant-testimonial-request' },
      { title: 'Certificate', status: 'Available', action: 'View', route: '/apply/certification' },
      { title: 'LinkedIn', status: 'Optional', action: 'Share', route: '/apply/applicant-linkedin-share', optional: true },
    ],
  },
};

export function isApplicantDashboardState(value: unknown): value is ApplicantDashboardState {
  return typeof value === 'string' && value in APPLICANT_DASHBOARD_STATE_TO_SCENARIO;
}
